version: '2'
services:
  mongodb:
    image: mongo
    volumes:
     - /opt/mongo_data:/data/db
  web:
    image: nextlink/releasemaster
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

