version: '2'
services:
  dbstore:
    image: mysql:5.7
    entrypoint: /bin/true
  db:
    image: mysql:5.7
    volumes_from:
      - dbstore
    environment:
      - "MYSQL_DATABASE=release"
      - "MYSQL_ROOT_PASSWORD=password"
  web:
    image: siweiwang/releasemaster
    ports:
      - "3000:3000"
    environment:
      - "DB_HOST=db"
    restart: always
    depends_on:
      - db
